cert_dir: "/home/jboivie/certs"
aap_installer_dir: "/home/jboivie/ansible-automation-platform-containerized-setup-bundle-2.5-16-aarch64"
aap_installer_tar: "/home/jboivie/ansible-automation-platform-containerized-setup-bundle-2.5-16-aarch64.tar"
home_dir: "/home/jboivie"